travis:
  secure:
    BINSTAR_TOKEN: cL00icsYxY/0uspbWsGLyhyb11xc0gBnv9rgZpekYq/h7RHwS+uF0uUEu9u8TqrjdvH26Vuk5lVa0qY+oC5Hwqu1ODGj/vSF0pM1B9lr9Z8jgYUGUWtpAuGul9UZHb3WCFrPxVL/lwc2VbNu/UBD7V42kVR3QzNPxVXr1aF7lKKL5p79dC36Jp5qsXUZ4+qFSrFmPT64JhsaNFWsUU4QO6F+qUqvdoYSRQ290qsqlkxrKIIPF7o/s2zJxgHJfK6UAlsiajczRtP/0Zx7jiWaTz/ST8czggJflXyUMxtSZOSRVSI1NFKmMZCo9vmspS9Fwcxrw/6rhJwTrpCjJpE9crAKlthfAh0edykX5Kyw4UF3tzvPKbV3eteRZKOThZpzCkcLTpy26rA2imR0m03vB9qnlPF+KB8A5247thmfTsG2EkfRnOeLVinX0n3CVMzKqd2kclViuhiY3XKFHnhNfIQgf+FUL3CqHMWIU9VkPBUah8zj7tX1rglRVG90Q5z+83XF+JmIPVvwQgXeZiHu2pcM4FR9voHpyUKw1XLPd0AkwPP7VPQBFYSLVJ7b/Q0tG84FYWN2+Q5n1mNFXp8FefotfXLiJK5barNT5o849o12JSpl8YWHxN9TgpzaHt/aTZapce8RvgEI3ZvAoLWI+9IsWFo5UPH6MB9MuywkXxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
