appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qgXkbRb1CfqhgwLc6wRb4S4Aww93Qkpo3liD0KDT3DCLcuQbfET3WRSst7CaW/WvrSnVPbFEf3jhxDET5UlqOczvY+i2QEKclXFgg1QIj4NyN6w7365hL2umU9MiF6SScIYUcHtEK55UeGA4jDj3WYUsUYYSnBxiHOncae/YJgX1vIqdtLbefZHOKxGXMG8ied6jiV6xlFDfqKFQ2C7E1kYJFm6KVSdd3QKdvXvcJqJM/MOjgQ5rQKyque341X6un2bAKp67oaOr+5VaNWKuTo4qD/yTknX0RMAPO06uvo4cy28KgoPqppMiCe/pyiC6tlcLfmiZZT222Ff+Dh+O033zx2ENFP9D8ygps4oRVI7Q3u5Nim2HrJwAJyCHF2XnjyXSA8dY7bvgIuK4rwjvtQonhwGCLFAIbgBWv3bfWjtvpmp0qwqVWvW3iPymFLT78CsFwXYbGBQcUo1NWapbej3ylXKmJWZMo5ftWri+00QgqPQyATsr6fMWwbgRmIPL000VEqXjVnSEp5mxjvUsJwqzkha+TiZJ+q7Yx0wvmw63vnFmViLMonYefxZpMHuZ6BxAej/pojr6pncMCxU3tIec7aZ2Uq35QHsYUu7sYp9TV4A+igZT+0qFxqykQ+GYhh+geG0N51z8DMxSLR/0FEJShRy14rfvw772EWZH1Dw=}
provider:
  win: azure
